# Site settings
title: Pengzhu Lin
email: plinai@connect.ust.hk
description: > # this means to ignore newlines until "baseurl:"
   Ph.D. from HKUST, 2024| M.S. & B.S. from HUST, 2020 & 2017
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pengzhulin.top" # the base hostname & protocol for your site
production_url: "https://www.pengzhulin.top"
github_username: pengzhulin
permalink: /blog/:year/:month/:title.html

twitter:
  username: pengzhulin

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
