# Site settings
title: Pengzhu Lin
email: plinai@connect.ust.hk
description: > # this means to ignore newlines until "baseurl:"
   Postdoctoral fellow at the Hong Kong University of Science and Technology. Ph.D. from HKUST| M.Eng. and B.Eng. from HUST
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.domoritz.de" # the base hostname & protocol for your site
production_url: "https://www.domoritz.de"
github_username: pengzhulin
permalink: /blog/:year/:month/:title.html

twitter:
  username: pengzhulin

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
